export const ValidatedReports: any = [
    {
        "id": "db4510ab-1b40-418a-b1a6-36efba0f3a7c",
        "val_cr_consecutive_id": 1,
        "val_cr_previous_id": 0,
        "val_cr_originalcase_id_fk": "ee085683-9706-49e3-94d4-d889bfb8341a",
        "val_cr_casetype_id_fk": 4,
        "val_cr_filingnumber": "0000000001",
        "val_cr_documentpatient": "22382782",
        "val_cr_doctypepatient": "CC",
        "val_cr_firstnamepatient": "MARIA",
        "val_cr_secondnamepatient": "CANDELARIA",
        "val_cr_firstlastnamepatient": "POLO",
        "val_cr_secondlastnamepatient": "BARRIOS",
        "val_cr_agepatient": 76,
        "val_cr_genderpatient": "F",
        "val_cr_epspatient": "SURA",
        "val_cr_admconsecutivepatient": 405,
        "val_cr_reporter_id_fk": 2222,
        "val_cr_eventtype_id_fk": 1,
        "val_cr_service_id_fk": 1,
        "val_cr_event_id_fk": 2,
        "val_cr_risktype_id_fk": 1,
        "val_cr_severityclasif_id_fk": 5,
        "val_cr_origin_id_fk": 1,
        "val_cr_suborigin_id_fk": 1,
        "val_cr_risklevel_id_fk": null,
        "val_cr_unit_id_fk": 1,
        "val_cr_description": "test_indicatingUnsafeCare",
        "val_cr_inmediateaction": "test1",
        "val_cr_materializedrisk": null,
        "val_cr_associatedpatient": true,
        "val_cr_validated": false,
        "val_cr_status": true,
        "createdAt": "2024-06-11T22:29:35.289Z",
        "updateAt": "2024-06-11T22:29:35.289Z",
        "deletedAt": null,
        "caseReportOriginal": {
            "id": "ee085683-9706-49e3-94d4-d889bfb8341a",
            "ori_cr_casetype_id_fk": 4,
            "ori_cr_filingnumber": "0000000001",
            "ori_cr_documentpatient": "22382782",
            "ori_cr_doctypepatient": "CC",
            "ori_cr_firstnamepatient": "MARIA",
            "ori_cr_secondnamepatient": "CANDELARIA",
            "ori_cr_firstlastnamepatient": "POLO",
            "ori_cr_secondlastnamepatient": "BARRIOS",
            "ori_cr_agepatient": 76,
            "ori_cr_genderpatient": "F",
            "ori_cr_epspatient": "SURA",
            "ori_cr_admconsecutivepatient": 405,
            "ori_cr_reporter_id_fk": 2222,
            "ori_cr_eventtype_id_fk": 1,
            "ori_cr_service_id_fk": 1,
            "ori_cr_event_id_fk": 2,
            "ori_cr_risktype_id_fk": 1,
            "ori_cr_severityclasif_id_fk": 5,
            "ori_cr_origin_id_fk": 1,
            "ori_cr_suborigin_id_fk": 1,
            "ori_cr_risklevel_id_fk": null,
            "ori_cr_unit_id_fk": 1,
            "ori_cr_description": "test_indicatingUnsafeCare",
            "ori_cr_inmediateaction": "test1",
            "ori_cr_materializedrisk": null,
            "ori_cr_associatedpatient": true,
            "ori_cr_status": true,
            "createdAt": "2024-06-11T22:29:35.289Z",
            "updateAt": "2024-06-11T22:29:35.289Z",
            "deletedAt": null
        },
        "log": [
            {
                "id": 478,
                "log_validatedcase_id_fk": "db4510ab-1b40-418a-b1a6-36efba0f3a7c",
                "log_user_id_fk": 2222,
                "log_action": "Registró el caso",
                "log_ip": "::1",
                "log_status": true,
                "createdAt": "2024-06-11T22:29:35.289Z",
                "updateAt": "2024-06-11T22:29:35.289Z",
                "deletedAt": null
            }
        ],
        "reportAnalystAssignment": [],
        "synergy": [],
        "caseType": {
            "id": 4,
            "cas_t_name": "Indicio de Atención Insegura",
            "cas_t_description": "Un acontecimiento o una circunstancia que pueden alertar acerca del incremento del riesgo de ocurrencia de un incidente o evento adverso.",
            "cas_t_status": true,
            "createdAt": "2024-05-10T16:41:09.871Z",
            "updateAt": "2024-05-10T16:41:09.871Z",
            "deletedAt": null
        }
    },
    {
        "id": "411fce6e-51f8-46bf-89cc-4f6088e0ad1a",
        "val_cr_consecutive_id": 1,
        "val_cr_previous_id": 0,
        "val_cr_originalcase_id_fk": "45055cde-188e-4e1e-b531-93c51816f353",
        "val_cr_casetype_id_fk": 5,
        "val_cr_filingnumber": "0000000002",
        "val_cr_documentpatient": "22382782",
        "val_cr_doctypepatient": "CC",
        "val_cr_firstnamepatient": "MARIA",
        "val_cr_secondnamepatient": "CANDELARIA",
        "val_cr_firstlastnamepatient": "POLO",
        "val_cr_secondlastnamepatient": "BARRIOS",
        "val_cr_agepatient": 76,
        "val_cr_genderpatient": "F",
        "val_cr_epspatient": "SURA",
        "val_cr_admconsecutivepatient": 405,
        "val_cr_reporter_id_fk": 2222,
        "val_cr_eventtype_id_fk": 1,
        "val_cr_service_id_fk": 1,
        "val_cr_event_id_fk": 2,
        "val_cr_risktype_id_fk": null,
        "val_cr_severityclasif_id_fk": 5,
        "val_cr_origin_id_fk": 1,
        "val_cr_suborigin_id_fk": 1,
        "val_cr_risklevel_id_fk": 1,
        "val_cr_unit_id_fk": 1,
        "val_cr_description": "test_complication",
        "val_cr_inmediateaction": "test1",
        "val_cr_materializedrisk": null,
        "val_cr_associatedpatient": true,
        "val_cr_validated": false,
        "val_cr_status": true,
        "createdAt": "2024-06-11T22:35:42.858Z",
        "updateAt": "2024-06-11T22:35:42.858Z",
        "deletedAt": null,
        "caseReportOriginal": {
            "id": "45055cde-188e-4e1e-b531-93c51816f353",
            "ori_cr_casetype_id_fk": 5,
            "ori_cr_filingnumber": "0000000002",
            "ori_cr_documentpatient": "22382782",
            "ori_cr_doctypepatient": "CC",
            "ori_cr_firstnamepatient": "MARIA",
            "ori_cr_secondnamepatient": "CANDELARIA",
            "ori_cr_firstlastnamepatient": "POLO",
            "ori_cr_secondlastnamepatient": "BARRIOS",
            "ori_cr_agepatient": 76,
            "ori_cr_genderpatient": "F",
            "ori_cr_epspatient": "SURA",
            "ori_cr_admconsecutivepatient": 405,
            "ori_cr_reporter_id_fk": 2222,
            "ori_cr_eventtype_id_fk": 1,
            "ori_cr_service_id_fk": 1,
            "ori_cr_event_id_fk": 2,
            "ori_cr_risktype_id_fk": null,
            "ori_cr_severityclasif_id_fk": 5,
            "ori_cr_origin_id_fk": 1,
            "ori_cr_suborigin_id_fk": 1,
            "ori_cr_risklevel_id_fk": 1,
            "ori_cr_unit_id_fk": 1,
            "ori_cr_description": "test_complication",
            "ori_cr_inmediateaction": "test1",
            "ori_cr_materializedrisk": null,
            "ori_cr_associatedpatient": true,
            "ori_cr_status": true,
            "createdAt": "2024-06-11T22:35:42.858Z",
            "updateAt": "2024-06-11T22:35:42.858Z",
            "deletedAt": null
        },
        "log": [
            {
                "id": 479,
                "log_validatedcase_id_fk": "411fce6e-51f8-46bf-89cc-4f6088e0ad1a",
                "log_user_id_fk": 2222,
                "log_action": "Registró el caso",
                "log_ip": "::1",
                "log_status": true,
                "createdAt": "2024-06-11T22:35:42.858Z",
                "updateAt": "2024-06-11T22:35:42.858Z",
                "deletedAt": null
            },
            {
                "id": 482,
                "log_validatedcase_id_fk": "411fce6e-51f8-46bf-89cc-4f6088e0ad1a",
                "log_user_id_fk": 8888,
                "log_action": "Asignado a analista",
                "log_ip": "::1",
                "log_status": true,
                "createdAt": "2024-06-11T22:38:03.716Z",
                "updateAt": "2024-06-11T22:38:03.716Z",
                "deletedAt": null
            }
        ],
        "reportAnalystAssignment": [
            {
                "id": 40,
                "ass_ra_validatedcase_id_fk": "411fce6e-51f8-46bf-89cc-4f6088e0ad1a",
                "ass_ra_position_id_fk": 1275,
                "ass_ra_documentanalyst": 1143145099,
                "ass_ra_status": true,
                "createdAt": "2024-06-11T22:38:03.729Z",
                "updateAt": "2024-06-11T22:38:03.729Z",
                "deletedAt": null
            }
        ],
        "synergy": [],
        "caseType": {
            "id": 5,
            "cas_t_name": "Complicaciones",
            "cas_t_description": "Resultado no deseado presentado a pesar del cumplimiento de los estándares de cuidado, atribuible a las condiciones propias del paciente.",
            "cas_t_status": true,
            "createdAt": "2024-05-10T16:41:15.395Z",
            "updateAt": "2024-05-10T16:41:15.395Z",
            "deletedAt": null
        }
    },
    {
        "id": "c8e31c40-bd5e-47cf-9cbf-09eac777312b",
        "val_cr_consecutive_id": 1,
        "val_cr_previous_id": 0,
        "val_cr_originalcase_id_fk": "dea8d684-135e-4986-b5ec-139b72a7c7e9",
        "val_cr_casetype_id_fk": 2,
        "val_cr_filingnumber": "0000000003",
        "val_cr_documentpatient": "22382782",
        "val_cr_doctypepatient": "CC",
        "val_cr_firstnamepatient": "MARIA",
        "val_cr_secondnamepatient": "CANDELARIA",
        "val_cr_firstlastnamepatient": "POLO",
        "val_cr_secondlastnamepatient": "BARRIOS",
        "val_cr_agepatient": 76,
        "val_cr_genderpatient": "F",
        "val_cr_epspatient": "SURA",
        "val_cr_admconsecutivepatient": 405,
        "val_cr_reporter_id_fk": 2222,
        "val_cr_eventtype_id_fk": 1,
        "val_cr_service_id_fk": 1,
        "val_cr_event_id_fk": 2,
        "val_cr_risktype_id_fk": null,
        "val_cr_severityclasif_id_fk": 5,
        "val_cr_origin_id_fk": 1,
        "val_cr_suborigin_id_fk": 1,
        "val_cr_risklevel_id_fk": 1,
        "val_cr_unit_id_fk": 1,
        "val_cr_description": "test_adverseEvent",
        "val_cr_inmediateaction": "test1",
        "val_cr_materializedrisk": null,
        "val_cr_associatedpatient": true,
        "val_cr_validated": false,
        "val_cr_status": true,
        "createdAt": "2024-06-11T22:35:56.319Z",
        "updateAt": "2024-06-11T22:35:56.319Z",
        "deletedAt": null,
        "caseReportOriginal": {
            "id": "dea8d684-135e-4986-b5ec-139b72a7c7e9",
            "ori_cr_casetype_id_fk": 2,
            "ori_cr_filingnumber": "0000000003",
            "ori_cr_documentpatient": "22382782",
            "ori_cr_doctypepatient": "CC",
            "ori_cr_firstnamepatient": "MARIA",
            "ori_cr_secondnamepatient": "CANDELARIA",
            "ori_cr_firstlastnamepatient": "POLO",
            "ori_cr_secondlastnamepatient": "BARRIOS",
            "ori_cr_agepatient": 76,
            "ori_cr_genderpatient": "F",
            "ori_cr_epspatient": "SURA",
            "ori_cr_admconsecutivepatient": 405,
            "ori_cr_reporter_id_fk": 2222,
            "ori_cr_eventtype_id_fk": 1,
            "ori_cr_service_id_fk": 1,
            "ori_cr_event_id_fk": 2,
            "ori_cr_risktype_id_fk": null,
            "ori_cr_severityclasif_id_fk": 5,
            "ori_cr_origin_id_fk": 1,
            "ori_cr_suborigin_id_fk": 1,
            "ori_cr_risklevel_id_fk": 1,
            "ori_cr_unit_id_fk": 1,
            "ori_cr_description": "test_adverseEvent",
            "ori_cr_inmediateaction": "test1",
            "ori_cr_materializedrisk": null,
            "ori_cr_associatedpatient": true,
            "ori_cr_status": true,
            "createdAt": "2024-06-11T22:35:56.319Z",
            "updateAt": "2024-06-11T22:35:56.319Z",
            "deletedAt": null
        },
        "log": [
            {
                "id": 480,
                "log_validatedcase_id_fk": "c8e31c40-bd5e-47cf-9cbf-09eac777312b",
                "log_user_id_fk": 2222,
                "log_action": "Registró el caso",
                "log_ip": "::1",
                "log_status": true,
                "createdAt": "2024-06-11T22:35:56.319Z",
                "updateAt": "2024-06-11T22:35:56.319Z",
                "deletedAt": null
            },
            {
                "id": 481,
                "log_validatedcase_id_fk": "c8e31c40-bd5e-47cf-9cbf-09eac777312b",
                "log_user_id_fk": 5555,
                "log_action": "Caso elevado a comité de sinergia",
                "log_ip": "::1",
                "log_status": true,
                "createdAt": "2024-06-11T22:36:45.481Z",
                "updateAt": "2024-06-11T22:36:45.481Z",
                "deletedAt": null
            }
        ],
        "reportAnalystAssignment": [],
        "synergy": [
            {
                "id": 71,
                "syn_validatedcase_id_fk": "c8e31c40-bd5e-47cf-9cbf-09eac777312b",
                "syn_programmingcounter": 0,
                "syn_evaluationdate": "2024-06-11T22:36:45.463Z",
                "syn_reschedulingdate": null,
                "syn_resolutiondate": null,
                "syn_status": false,
                "createdAt": "2024-06-11T22:36:45.465Z",
                "updateAt": "2024-06-11T22:36:45.465Z",
                "deletedAt": null
            }
        ],
        "caseType": {
            "id": 2,
            "cas_t_name": "Evento Adverso",
            "cas_t_description": "Es la lesión o daño producido a un paciente durante el proceso de atención de forma no intencional.",
            "cas_t_status": true,
            "createdAt": "2024-05-10T16:40:54.745Z",
            "updateAt": "2024-05-10T16:40:54.745Z",
            "deletedAt": null
        }
    }
]